export const GET_ALL_BILLS_SAGA = 'GET_ALL_BILLS_SAGA';
export const GET_ALL_BILLS = 'GET_ALL_BILLS';
export const GET_DETAIL_BILL_BY_ID_SAGA = 'GET_DETAIL_BILL_BY_ID_SAGA';
export const GET_DETAIL_BILL_BY_ID = 'GET_DETAIL_BILL_BY_ID';


//
export const GET_ALL_PRODUCT_BILLS_SAGA = 'GET_ALL_PRODUCT_BILLS_SAGA';
export const GET_ALL_PRODUCT_BILLS = 'GET_ALL_PRODUCT_BILLS';
export const DELETE_PRODUCT_BILLS = 'DELETE_PRODUCT_BILLS';
export const DELETE_ALL_PRODUCT_BILLS = 'DELETE_ALL_PRODUCT_BILLS';

//
export const INSERT_BILLS_SAGA = 'INSERT_BILLS_SAGA';
//
export const INSERT_PRODUCTBILL_SAGA = 'INSERT_PRODUCTBILL_SAGA';
export const INSERT_NEWPRODUCTBILL_SAGA = 'INSERT_NEWPRODUCTBILL_SAGA';

//
export const UPDATE_BILL_SAGA = 'UPDATE_BILL_SAGA';
export const EDIT_BILL = 'EDIT_BILL';





//
export const DELETE_BILLS_SAGA = 'DELETE_BILLS_SAGA';
export const DETAIL_Detail_BILLS_SAGA = 'DETAIL_Detail_BILLS_SAGA';
//

