export const GET_ALL_SUPPLIER_SAGA = 'GET_ALL_SUPPLIER_SAGA';
export const GET_ALL_SUPPLIER = 'GET_ALL_SUPPLIER';

//

//
export const INSERT_SUPPLIER_SAGA = 'INSERT_SUPPLIER_SAGA';
//
export const UPDATE_SUPPLIER_SAGA = 'UPDATE_SUPPLIER_SAGA';

//
export const DELETE_SUPPLIER_SAGA = 'DELETE_SUPPLIER_SAGA';
//
