export const GET_ALL_CATEGORIES_SAGA = 'GET_ALL_CATEGORIES_SAGA';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';

//
export const GET_ALL_PRODUCTS_SAGA = 'GET_ALL_PRODUCTS_SAGA';
export const GET_ALL_PRODUCTS= 'GET_ALL_PRODUCTS';
export const GET_PRODUCT_DETAIL= 'GET_PRODUCT_DETAIL';
export const GET_PRODUCT_BY_ID_CATEGORY_SAGA= 'GET_PRODUCT_BY_ID_CATEGORY_SAGA';
export const GET_ALL_NEWS_SAGA= 'GET_ALL_NEWS_SAGA';
export const GET_ALL_NEWS= 'GET_ALL_NEWS';
export const GET_ALL_NEWS_DETAIL_SAGA= 'GET_ALL_NEWS_DETAIL_SAGA';
export const GET_ALL_NEWS_DETAIL= 'GET_ALL_NEWS_DETAIL';
export const GET_LIST_HISTORY_SAGA= 'GET_LIST_HISTORY_SAGA';
export const GET_LIST_HISTORY= 'GET_LIST_HISTORY';

export const    DAT_LAI_SAGA= 'DAT_LAI_SAGA';
export const    HUY_DON_HANG_SAGA= 'HUY_DON_HANG_SAGA';