export const GET_ALL_CATEGORIES_SAGA = 'GET_ALL_CATEGORIES_SAGA';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';

//
export const GET_CATEGORIES_BY_ID_SAGA = 'GET_CATEGORIES_BY_ID_SAGA';
export const GET_CATEGORIES_BY_ID = 'GET_CATEGORIES_BY_ID';
//
export const INSERT_CATEGORIES_SAGA = 'INSERT_CATEGORIES_SAGA';
//
export const UPDATE_CATEGORIES_SAGA = 'UPDATE_CATEGORIES_SAGA';

//
export const DELETE_CATEGORIES_SAGA = 'DELETE_CATEGORIES_SAGA';
//
