export const THONG_KE_THU_NHAP_THEO_NAM = 'THONG_KE_THU_NHAP';
export const THONG_KE_THU_NHAP_THEO_NAM_SAGA = 'THONG_KE_THU_NHAP_THEO_NAM_SAGA';
export const THONG_KE_THU_NHAP_THEO_THANG = 'THONG_KE_THU_NHAP_THEO_THANG';
export const THONG_KE_THU_NHAP_THEO_THANG_SAGA = 'THONG_KE_THU_NHAP_THEO_THANG_SAGA';
export const THONG_KE_HOA_DON_NHAP_DXL = 'THONG_KE_HOA_DON_NHAP_DXL';
export const THONG_KE_HOA_DON_NHAP_DXL_SAGA = 'THONG_KE_HOA_DON_NHAP_DXL_SAGA';

//
export const THONG_KE_CHI_TIEU_THEO_NAM = 'THONG_KE_CHI_TIEU_THEO_NAM';
export const THONG_KE_CHI_TIEU_THEO_NAM_SAGA = 'THONG_KE_CHI_TIEU_THEO_NAM_SAGA';
export const THONG_KE_CHI_TIEU_THEO_THANG = 'THONG_KE_CHI_TIEU_THEO_THANG';
export const THONG_KE_CHI_TIEU_THEO_THANG_SAGA = 'THONG_KE_CHI_TIEU_THEO_THANG_SAGA';
export const THONG_KE_HOA_DON_BAN_DXL = 'THONG_KE_HOA_DON_BAN_DXL';
export const THONG_KE_HOA_DON_BAN_DXL_SAGA = 'THONG_KE_HOA_DON_BAN_DXL_SAGA';
export const THONG_KE_HOA_DON_BAN_DXL_THEO_THANG_SAGA = 'THONG_KE_HOA_DON_BAN_DXL_THEO_THANG_SAGA';
export const THONG_KE_HOA_DON_BAN_DXL_THEO_THANG = 'THONG_KE_HOA_DON_BAN_DXL_THEO_THANG';


//
export const THONG_KE_TOP_5_CUSTOMER_MAX_TOTAL = 'THONG_KE_TOP_5_CUSTOMER_MAX_TOTAL';
export const THONG_KE_TOP_5_CUSTOMER_MAX_TOTAL_SAGA = 'THONG_KE_TOP_5_CUSTOMER_MAX_TOTAL_SAGA';
export const THONG_KE_TOP_5_PRODUCT_BC = 'THONG_KE_TOP_5_PRODUCT_BC';
export const THONG_KE_TOP_5_PRODUCT_BC_SAGA = 'THONG_KE_TOP_5_PRODUCT_BC_SAGA';


//

export const THONG_KE_THU_NHAP_THEO_LOAI = 'THONG_KE_THU_NHAP_THEO_LOAI';
export const THONG_KE_THU_NHAP_THEO_LOAI_SAGA = 'THONG_KE_THU_NHAP_THEO_LOAI_SAGA';
