export const GET_ALL_PRODUCT_SAGA = 'GET_ALL_PRODUCT_SAGA';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';

//
export const GET_PRODUCT_BY_ID_SAGA = 'GET_PRODUCT_BY_ID_SAGA';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
//
export const INSERT_PRODUCT_SAGA = 'INSERT_PRODUCT_SAGA';
//
export const UPDATE_PRODUCT_SAGA = 'UPDATE_PRODUCT_SAGA';

//
export const DELETE_PRODUCT_SAGA = 'DELETE_PRODUCT_SAGA';
//
